sudo: required

dist: trusty

services:
  - docker

addons:
  chrome: stable

language: node_js

node_js:
  - '8'
  - '10'

cache:
  directories:
    - packages/nightwatch-api/node_modules
    - packages/website/node_modules
    - packages/node-example/node_modules
    - packages/jest-example/node_modules
    - packages/cucumber-example/node_modules
    - packages/cucumber-selenium-example/node_modules
    - packages/cucumber-selenium-hub-example/node_modules

branches:
  only:
    - master

notifications:
  email: false

install:
  - cd packages/nightwatch-api
  - npm ci
  - npm run pack-into-examples

before_script:
  - jdk_switcher use openjdk8
  - java -version
  - google-chrome --product-version

script:
  - npm run lint
  - npm run type-check
  - npm run test:coverage
  - npm run check-webdriver-stopped
  - cd ..
  - cd node-example && npm test && cd ../nightwatch-api && npm run check-webdriver-stopped && cd ..
  - cd jest-example && npm test && cd ../nightwatch-api && npm run check-webdriver-stopped && cd ..
  - cd cucumber-example && npm test && cd ../nightwatch-api && npm run check-webdriver-stopped && cd ..
  # - cd cucumber-selenium-example && npm test && cd ../nightwatch-api && npm run check-webdriver-stopped && cd ..
  - cd cucumber-selenium-hub-example && docker-compose up --abort-on-container-exit && cd ..
  - cd cucumber-browserstack-example && npm test && cd ..

after_success:
  - cd nightwatch-api
  - npm run test:coveralls
  - cd ..

before_deploy:
  - cd website
  - npm i

deploy:
  provider: script
  script: npm run deploy -- --auth $NETLIFY_ACCESS_TOKEN
  skip_cleanup: true
  on:
    branch: master
    node: '10'
